services:
  gogogo-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ../config:/app/config
      - ../storage:/app/storage
    restart: unless-stopped

  postgres:
    image: postgis/postgis:15-3.4
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gogogo
    volumes:
      - ../scripts/postgres:/var/lib/postgresql/data
    restart: unless-stopped
